export const codeMaps = {
  school: {
    Abjuration: "AB",
    Conjuration: "CJ",
    Divination: "DV",
    Enchantment: "EC",
    Evocation: "EV",
    Illusion: "IL",
    Necromancy: "NC",
    Transmutation: "TM",
    Dunamancy: "DU",
  },
  classes: {
    Artificer: "A",
    Bard: "B",
    Cleric: "C",
    Druid: "D",
    Paladin: "P",
    Ranger: "R",
    Sorcerer: "S",
    Warlock: "W",
    Wizard: "Z",
  },
  effect: {
    None: "NO",
    Combat: "CT",
    Control: "CL",
    Utility: "UT",
    Creation: "CR",
    Buff: "BF",
    Communication: "CM",
    Healing: "HL",
    Foreknowledge: "FK",
    Detection: "DT",
    Charmed: "CH",
    Debuff: "DB",
    Frightened: "FT",
    Blinded: "BI",
    Prone: "PR",
    Social: "SO",
    Shapechanging: "SC",
    Deception: "DC",
    Restrained: "RS",
    Movement: "MV",
    Exploration: "EX",
    Summoning: "SM",
    Warding: "WD",
    Unconscious: "UC",
    Dunamancy: "DM",
    Invisible: "IV",
    Teleportation: "TL",
    Deafened: "DF",
    Additional: "AD",
    Negation: "NG",
    Banishment: "BS",
    Environment: "EN",
    Stunned: "ST",
    Petrified: "PF",
    Paralyzed: "PZ",
    Poison: "PO",
    Thunder: "TH",
    Psychic: "PS",
    Radiant: "RD",
    Bludgeoning: "BG",
    Fire: "FR",
    Force: "FC",
    Acid: "AC",
    Necrotic: "NT",
    Cold: "CO",
    Lightning: "LI",
    Piercing: "PI",
    Slashing: "SL",
  },
  castingTime: {
    "1 Reaction": "A",
    "1 Bonus Action": "B",
    "1 Action": "C",
    "1 Minute": "D",
    "10 Minutes": "E",
    "1 Hour": "F",
    "8 Hours": "G",
    "12 Hours": "H",
    "24 Hours": "I",
    Special: "J",
  },
  range: {
    Self: "11",
    "Self (5 ft)": "12",
    "Self (15 ft)": "13",
    "Self (30 ft)": "14",
    "Self (60 ft)": "15",
    Touch: "16",
    "5 ft": "17",
    "10 ft": "18",
    "15 ft": "19",
    "20 ft": "20",
    "30 ft": "21",
    "40 ft": "22",
    "50 ft": "23",
    "60 ft": "24",
    "90 ft": "25",
    "100 ft": "26",
    "120 ft": "27",
    "150 ft": "28",
    "200 ft": "29",
    "300 ft": "30",
    "500 ft": "31",
    "1000 ft": "32",
    "1 mile": "33",
    "5 miles": "34",
    "500 miles": "35",
    Sight: "36",
    Unlimited: "37",
  },
  duration: {
    Instantaneous: "A",
    "1 Round": "B",
    "6 Rounds": "C",
    "1 Minute": "D",
    "10 Minutes": "E",
    "1 Hour": "F",
    "2 Hours": "G",
    "8 Hours": "H",
    "24 Hours": "I",
    "7 Days": "J",
    "10 Days": "K",
    "30 Days": "L",
    "Until Dispelled": "M",
    Special: "N",
    "Until Dispelled or Triggered": "O",
  },
  area: {
    None: "11",
    "Line 30 ft": "12",
    "Line 60 ft": "13",
    "Line 100 ft": "14",
    "Sphere 5 ft": "15",
    "Sphere 10 ft": "16",
    "Sphere 15 ft": "17",
    "Sphere 20 ft": "18",
    "Sphere 30 ft": "19",
    "Sphere 40 ft": "20",
    "Sphere 60 ft": "21",
    "Sphere 5 miles": "22",
    "Cone 15 ft": "23",
    "Cone 30 ft": "24",
    "Cone 60 ft": "25",
    "Cylinder 5 ft": "26",
    "Cylinder 10 ft": "27",
    "Cylinder 20 ft": "28",
    "Cylinder 30 ft": "29",
    "Cylinder 40 ft": "30",
    "Cylinder 50 ft": "31",
    "Cylinder 60 ft": "32",
    "Square 5 ft": "33",
    "Square 10 ft": "34",
    "Square 20 ft": "35",
    "Cube 1 ft": "36",
    "Cube 5 ft": "37",
    "Cube 10 ft": "38",
    "Cube 15 ft": "39",
    "Cube 20 ft": "40",
    "Cube 30 ft": "41",
    "Cube 40 ft": "42",
    "Cube 60 ft": "43",
    "Cube 100 ft": "44",
    "Cube 150 ft": "45",
    "Cube 200 ft": "46",
    "2,500 ft^2": "47",
    "40,000 ft^2": "48",
    "Square 1 mile": "49",
  },
  materialType: {
    None: "NN",
    Trivial: "TV",
    Costed: "CS",
    Consumed: "CM",
  },
  attackSave: {
    None: "A",
    "STR Save": "B",
    "CON Save": "C",
    "DEX Save": "D",
    "INT Save": "E",
    "WIS Save": "F",
    "CHA Save": "G",
    "Melee Attack": "H",
    "Ranged Attack": "I",
  },
};

export function reverseLookup(map, value, fallback = "Unknown") {
  return Object.keys(map).find((key) => map[key] === value) || fallback;
}
